  version: '3.10'

  services:

    gcloud:
      image: google/cloud-sdk:latest
      volumes:
        - gcp-creds:/creds
        - .:/app
      working_dir: /app
      environment:
        - CLOUDSDK_CONFIG=/creds

  volumes:
    gcp-creds: